overrides:
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vitest: npm:@voidzero-dev/vite-plus-test@latest

onlyBuiltDependencies:
  - esbuild
  - workerd

minimumReleaseAge: 0

allowBuilds:
  esbuild: true
  msgpackr-extract: false
  sharp: false
  workerd: true
